spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  expiration_time: ${JWT_VALID_TIME}
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
